#+TITLE: Hankook Lee
#+OPTIONS: num:nil toc:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="main.css" />
#+HTML_HEAD: <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
#+HTML_HEAD: <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

#+BEGIN_EXPORT html
hankook.lee at skku.edu
/ <a href="https://github.com/hankook">Github</a>
/ <a href="https://scholar.google.co.kr/citations?user=CgqswXUAAAAJ">Google Scholar</a>
#+END_EXPORT

I am an assistant professor in [[https://cse.skku.edu][Department of Computer Science and Engineering at Sungkyunkwan University]]. Prior to this, I worked at [[https://www.lgresearch.ai][LG AI Research]] as a Research Scientist and Korea Advanced Institute of Science and Technology ([[https://kaist.ac.kr][KAIST]]) as a Postdoctoral Researcher. I completed my Ph.D. degree in the School of Electrical Engineering at [[https://kaist.ac.kr][KAIST]], advised by Prof. [[https://alinlab.kaist.ac.kr/shin.html][Jinwoo Shin]].

I am interested in improving the *_efficiency of deep learning_*. Specifically, my research has focused on data-efficient deep learning, including self-supervised learning, few-shot learning, and transfer learning. I am also interested in solving real-world problems on various data domains such as computer vision, chemistry, and tabular data.

If you are interested in joining our lab, send me an email with your transcript and CV.

* Publications
:PROPERTIES:
:HTML_CONTAINER_CLASS: publications
:END:

*J*: Journal / *C*: Conference / *W*: Workshop / *\star*: equal contribution

- [C15] Learning Equi-angular Representations for Online Continual Learning ::
  Minhyuk Seo, Hyunseo Koh, Wonje Jeung, Min Jae Lee, San Kim, *_Hankook Lee_*, Sungjun Cho, Sungik Choi, Hyunwoo Kim, Jonghyun Choi \\
  Conference on Computer Vision and Pattern Recognition (*CVPR*), 2024
- [J1/W] Few-shot Anomaly Detection via Personalization ::
  Sangkyung Kwak, Jongheon Jeong, *_Hankook Lee_*, Woohyuck Kim, Dongho Seo, Woojin Yun, Wonjin Lee, Jinwoo Shin \\
  IEEE Access, 2024 \\
  ICML Workshop on New Frontiers in Adversarial Machine Learning (*AdvML-Frontiers*), 2023 \\
  [[[https://ieeexplore.ieee.org/document/10401164][paper]]]
- [C14] Projection Regret: Reducing Background Bias for Novelty Detection via Diffusion Models ::
  Sungik Choi, *_Hankook Lee_*, Honglak Lee, Moontae Lee \\
  Neural Information Processing Systems (*NeurIPS*), 2023 \\
  [[[https://openreview.net/forum?id=3qHlPqzjM1][paper]]]
- [W3] Diffusion-based Semantic-Discrepant Outlier Generation for Out-of-Distribution Detection ::
  Suhee Yoon\star, Sanghyu Yoon\star, *_Hankook Lee_*, Sangjun Han, Ye Seul Sim, Kyungeun Lee, Hyeseung Cho, Woohyung Lim \\
  NeurIPS Workshop on Synthetic Data Generation with Generative AI (*SyntheticData4ML*), 2023 \\
  [[[https://openreview.net/forum?id=0jAd2k8JV4][paper]]]
- [W2] Mixed-Curvature Transformers for Graph Representation Learning ::
  Sungjun Cho, Seunghyuk Cho, Sungwoo Park, *_Hankook Lee_*, Honglak Lee, Moontae Lee \\
  ICML Workshop on Topology, Algebra, and Geometry in Machine Learning (*TAG-ML*), 2023 \\
  [[[https://openreview.net/forum?id=DFnk58DwTE][paper]]]
- [W1] Fragment-based Multi-view Molecular Contrastive Learning ::
  Seojin Kim\star, Jaehyun Nam\star, Junsu Kim, *_Hankook Lee_*, Sungsoo Ahn, Jinwoo Shin \\
  ICLR Workshop on Machine Learning for Materials (*ML4Materials*), 2023 \\
  [[[https://openreview.net/forum?id=9lGwd4q8KJc][paper]]]
- [C13/W] Enhancing Multiple Reliability Measures via Nuisance-extended Information Bottleneck ::
  Jongheon Jeong, Sihyun Yu, *_Hankook Lee_*, Jinwoo Shin \\
  Computer Vision and Pattern Recognition (*CVPR*), 2023 \\
  ECCV Workshop on Out-of-distribution Generalization in Computer Vision (*ECCVW-OOD-CV*), 2022 \\
  [[[https://openaccess.thecvf.com/content/CVPR2023/papers/Jeong_Enhancing_Multiple_Reliability_Measures_via_Nuisance-Extended_Information_Bottleneck_CVPR_2023_paper.pdf][paper]]] [[[https://arxiv.org/abs/2303.14096][arxiv]]]
- [C12/W] STUNT: Few-shot Tabular Learning with Self-generated Tasks from Unlabeled Tables ::
  Jaehyun Nam, Jihoon Tack, Kyungmin Lee, *_Hankook Lee_*, Jinwoo Shin \\
  International Conference on Learning Representations (*ICLR*), /Spotlight presentation/, 2023 \\
  Neural Information Processing Systems Workshop on Table Representation Learning (*NeurIPSW-TRL*), 2022 \\
  Samsung Humantech Paper Awards, Bronze Prize, 2023 \\
  [[[https://openreview.net/forum?id=_xlsjehDvlY][paper]]] [[[https://github.com/jaehyun513/STUNT][code]]]
- [C11/W] Unsupervised Meta-learning via Few-shot Pseudo-supervised Contrastive Learning ::
  Huiwon Jang\star, *_Hankook Lee_*\star, Jinwoo Shin \\
  International Conference on Learning Representations (*ICLR*), /Spotlight presentation/, 2023 \\
  Neural Information Processing Systems Workshop on Meta-Learning (*NeurIPSW-MetaLearn*), 2022 \\
  [[[https://openreview.net/forum?id=TdTGGj7fYYJ][paper]]] [[[https://arxiv.org/abs/2303.00996][arxiv]]] [[[https://github.com/alinlab/PsCo][code]]]
- [C10/W] Guiding Energy-based Models via Contrastive Latent Variables ::
  *_Hankook Lee_*, Jongheon Jeong, Sejun Park, Jinwoo Shin \\
  International Conference on Learning Representations (*ICLR*), /Spotlight presentation/, 2023 \\
  Neural Information Processing Systems Workshop on Self-Supervised Learning (*NeurIPSW-SSL*), /Oral Presentation/, 2022 \\
  [[[https://openreview.net/forum?id=CZmHHj9MgkP][paper]]] [[[https://arxiv.org/abs/2303.03023][arxiv]]] [[[https://github.com/hankook/CLEL][code]]]
- [C9] Meta-Learning with Self-Improving Momentum Target ::
  Jihoon Tack, Jongjin Park, *_Hankook Lee_*, Jaeho Lee, Jinwoo Shin \\
  Neural Information Processing Systems (*NeurIPS*), 2022 \\
  [[[https://openreview.net/forum?id=FCNMbF_TsKm][paper]]] [[[https://arxiv.org/abs/2210.05185][arxiv]]] [[[https://jihoontack.github.io/assets/simt_slide.pdf][slide]]] [[[https://jihoontack.github.io/assets/simt_poster.pdf][poster]]] [[[https://github.com/jihoontack/SiMT][code]]]
- [C8] Patch-level Representation Learning for Self-supervised Vision Transformers ::
  Sukmin Yun, *_Hankook Lee_*, Jaehyung Kim, Jinwoo Shin \\
  Computer Vision and Pattern Recognition (*CVPR*), /Oral Presentation/, 2022 \\
  [[[https://openaccess.thecvf.com/content/CVPR2022/html/Yun_Patch-Level_Representation_Learning_for_Self-Supervised_Vision_Transformers_CVPR_2022_paper.html][paper]]] [[[https://arxiv.org/abs/2206.07990][arxiv]]] [[[file:assets/poster_selfpatch.pdf][poster]]] [[[https://github.com/alinlab/SelfPatch][code]]]
- [C7/W] Improving Transferability of Representations via Augmentation-Aware Self-Supervision ::
  *_Hankook Lee_*, Kibok Lee, Kimin Lee, Honglak Lee, Jinwoo Shin \\
  Neural Information Processing Systems (*NeurIPS*), 2021 \\
  ICML 2021 Workshop: Self-Supervised Learning for Reasoning and Perception \\
  [[[https://openreview.net/forum?id=U34rQjnImpM][paper]]] [[[https://arxiv.org/abs/2111.09613][arxiv]]] [[[file:assets/AugSelf_NeurIPS2021_slide.pdf][slide]]] [[[file:assets/AugSelf_NeurIPS2021_poster.pdf][poster]]] [[[https://github.com/hankook/AugSelf][code]]]
- [C6] Self-Improved Retrosynthetic Planning ::
  Junsu Kim, Sungsoo Ahn, *_Hankook Lee_*, Jinwoo Shin \\
  International Conference on Machine Learning (*ICML*), 2021 \\
  [[[http://proceedings.mlr.press/v139/kim21b.html][paper]]] [[[https://arxiv.org/abs/2106.04880][arxiv]]] [[[https://icml.cc/media/icml-2021/Slides/10749.pdf][slide]]] [[[https://drive.google.com/file/d/1sbVoaw6eSYPK4WUxW34FNakfdwmlgcVu/view][poster]]] [[[https://github.com/junsu-kim97/self_improved_retro][code]]]
- [C5/W] RetCL: A Selection-based Approach for Retrosynthesis via Contrastive Learning ::
  *_Hankook Lee_*, Sungsoo Ahn, Seung-Woo Seo, You Young Song, Eunho Yang, Sung Ju Hwang, Jinwoo Shin \\
  International Joint Conference on Artificial Intelligence (*IJCAI*), 2021 \\
  NeurIPS Workshop for Machine Learning for Molecules, 2020 \\
  [[[https://www.ijcai.org/proceedings/2021/0368.pdf][paper]]] [[[https://arxiv.org/abs/2105.00795][arxiv (long version)]]] [[[file:assets/RetCL_IJCAI2021_slide.pdf][slide]]] [[[file:assets/RetCL_IJCAI2021_poster.pdf][poster]]] [[[https://github.com/hankook/RetCL][code]]]
- [C4] GTA: Graph Truncated Attention for Retrosynthesis ::
  Seung-Woo Seo\star, You Young Song\star, June Yong Yang, Seohui Bae, *_Hankook Lee_*, Jinwoo Shin, Sung Ju Hwang, Eunho Yang \\
  AAAI Conference on Artificial Intelligence (*AAAI*), 2021 \\
  [[[https://ojs.aaai.org/index.php/AAAI/article/view/16131][paper]]]
- [C3] Guiding Deep Molecular Optimization with Genetic Exploration ::
  Sungsoo Ahn, Junsu Kim, *_Hankook Lee_*, Jinwoo Shin \\
  Neural Information Processing Systems (*NeurIPS*), 2020 \\
  [[[https://papers.nips.cc/paper/2020/hash/8ba6c657b03fc7c8dd4dff8e45defcd2-Abstract.html][paper]]] [[[https://arxiv.org/abs/2007.04897][arxiv]]] [[[https://github.com/sungsoo-ahn/genetic-expert-guided-learning][code]]]
- [C2] Self-supervised Label Augmentation via Input Transformations ::
  *_Hankook Lee_*, Sung Ju Hwang, Jinwoo Shin \\
  International Conference on Machine Learning (*ICML*), 2020 \\
  Qualcomm-KAIST Innovation Awards, 2019 \\
  [[[http://proceedings.mlr.press/v119/lee20c.html][paper]]] [[[https://arxiv.org/abs/1910.05872][arxiv]]] [[[https://github.com/hankook/SLA][code]]] [[[https://icml.cc/virtual/2020/poster/6093][talk]]]
- [C1] Learning What and Where to Transfer ::
  Yunhun Jang\star, *_Hankook Lee_*\star, Sung Ju Hwang, Jinwoo Shin \\
  International Conference on Machine Learning (*ICML*), 2019 \\
  [[[http://proceedings.mlr.press/v97/jang19b.html][paper]]] [[[https://arxiv.org/abs/1905.05901][arxiv]]] [[[https://github.com/alinlab/L2T-ww][code]]] [[[https://icml.cc/media/Slides/icml/2019/103(13-09-00)-13-10-05-5011-learning_what_a.pdf][slide]]] [[[https://slideslive.com/38917771/supervised-and-transfer-learning][talk]] 55:14~59:09]

* Work Experience
- Sungkyunkwan University ::
  Suwon, South Korea, 2024. 03 - present \\
  Assistant Professor
- LG AI Research ::
  Seoul, South Korea, 2023. 02 - 2024. 02 \\
  Research Scientist
- Korea Advanced Institute of Science and Technology (KAIST) ::
  Seongnam, South Korea, 2022. 09 - 2023. 02 \\
  Postdoctoral Researcher
- Samsung Advanced Institute of Technology (SAIT) ::
  Suwon, South Korea, 2020. 01 - 2020. 03 \\
  Visiting Student
- Frograms Inc. (changed to Watcha Inc. @ 2018) ::
  Seoul, South Korea, 2013. 08 - 2014. 12 \\
  Research and Development Engineer

* Education
- Korea Advanced Institute of Science and Technology (KAIST) ::
  Daejeon, South Korea, 2016. 03 - 2022. 08 \\
  M.S. & Ph.D. in Electrical Engineering (advisor: [[https://alinlab.kaist.ac.kr/shin.html][Jinwoo Shin]])
- Korea Advanced Institute of Science and Technology (KAIST) ::
  Daejeon, South Korea, 2010. 02 - 2016. 02 \\
  B.S. in Mathematical Science and Computer Science (double major)

* Awards
- Qualcomm-KAIST Innovation Awards (2019)
- International Collegiate Programming Contest (ICPC)
  - Asia Daejeon Regional: *Grand* Prize (1st place, 2012), *Gold* Prize (2nd place, 2010)
  - Participated in ICPC World Finals 2013
- Korea Olympiad in Informatics (KOI) : *Gold* Prize (2009)

* Services
- Conference Reviewer:
  - *ICLR* (2020-2024)
  - *NeurIPS* (2020-2023)
  - *ICML* (2021-2024)
  - *AAAI* (2022-2024)
  - Self-supervised Learning Workshops (ICML 2021, NeurIPS 2021-2022, ECCV 2022)
- Journal Reviewer:
  - ACM *ToMPECS*
  - IEEE *TPAMI*
  - Journal of Machine Learning Research (*JMLR*)
  - Nature Communications
